### ISSUE TITLE
if-you-need-to-delete-this-open-an-issue-async-disk-cache

### ISSUE THREAD

**Issue by Jernik** [stefanpenner/async-disk-cache#36]
I have encountered this permission denied error fairly often while using ember cli on a shared environment with other ember developers. What other information do you need from me?

**Comment by rwjblue** [comment]
Can you share the error and stack trace?

**Comment by Jernik** [comment]
lukem@OVERMIND:/raided/Luke/poppays/popular-media-web-app$ ember s
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

Livereload server on http://localhost:49153
Serving on http://localhost:4200/
File: modules/ember-inflector/index.js
The Broccoli Plugin: [Babel] failed with:
Error: EACCES: permission denied, mkdir '/tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache/fa78b2531346d21c566a732afe2ad6bcbe44a2c4'
    at Error (native)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/raided/Luke/poppays/popular-media-web-app/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/raided/Luke/poppays/popular-media-web-app/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new Babel (/raided/Luke/poppays/popular-media-web-app/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/raided/Luke/poppays/popular-media-web-app/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.registry.add.toTree (/raided/Luke/poppays/popular-media-web-app/node_modules/ember-cli-babel/index.js:30:52)
    at /raided/Luke/poppays/popular-media-web-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/raided/Luke/poppays/popular-media-web-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/raided/Luke/poppays/popular-media-web-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at CoreObject.extend.preprocessJs (/raided/Luke/poppays/popular-media-web-app/node_modules/ember-cli/lib/models/addon.js:818:25)


Is this what you're looking for?

**Comment by Jernik** [comment]
Note: running 
`chmod` 777 /tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache/ 
stops this issue from occurring, and I think this is because some other user originally created this folder

**Comment by rwjblue** [comment]
Ahh, interesting!  We do currently set the permissions do the directory after creating it, but we are actually using `chmod 0775` today. I _believe_ that the 775 is actually correct (otherwise we would have some security implications on shared machines), but we should probably create sub-dirs per user or something if we are going to use user specific permissions.

@stefanpenner - Thoughts on using `/tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache/$USER` (via something like `username` npm package)?

**Comment by kbower** [comment]
Having the same problem.  Should be a separate cache based on os user:
`/tmp/<USER>/if-you-need-to-delete-this-open-an-issue-async-disk-cache/`

**Comment by robneville73** [comment]
Yup, needs to be cached per user. Same issue.

**Comment by stefanpenner** [comment]
> @stefanpenner - Thoughts on using /tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache/$USER (via something like username npm package)?

This sounds good.

**Comment by Stevko-sk** [comment]
No. Not /tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache/$USER. Use /tmp/$USER/if-you-need-to-delete-this-open-an-issue-async-disk-cache/ if you really have to use fixed dir name.
When first user runs it, it will create if-you-need-to-delete-this-open-an-issue-async-disk-cache as that user and any other user will not be able to create their subdirectory.
And in any case: one should use a function to create tmp directories (there is mkstemp in C, tempfile library in python). Otherwise there still may be problems even when one user runs several builds in parallel.
