### ISSUE TITLE
whoami problem on windows with yarn

### ISSUE THREAD

**Issue by polarctos** [stefanpenner/async-disk-cache#56]
A couple of weeks ago the code started to use 'whoami' instead of the username node module: https://github.com/stefanpenner/async-disk-cache/commit/019f24267975a8abaf7f752015dd62750ac19fd6

Since then I can no longer use it using yarn on my Windows 7 machine in the context of an ember build.
Version: async-disk-cache@^1.0.0:   version "1.3.1"

```
yarn run serve
yarn run v0.23.4
$ ember serve --proxy http://127.0.0.1:8080
'whoami' is not recognized as an internal or external command,
operable program or batch file.
File: C:\Windows\system32\cmd.exe
Command failed: whoami
'whoami' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed: whoami
'whoami' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.<anonymous> (C:\....\node_modules\async-disk-cache\index.js:25:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dbashford** [comment]
This started happening to us with our builds over the weekend

**Comment by polarctos** [comment]
Thanks a lot, [v1.3.2](https://github.com/stefanpenner/async-disk-cache/releases/tag/v1.3.2) fixed the problem.
